filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/cowrie/cowrie.json*
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: cowrie
      source_host: ${HOSTNAME}
    fields_under_root: true

output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
  compression_level: 3
  bulk_max_size: 2048

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

monitoring.enabled: false
